[project]
name = "simulated-bifurcation"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "tqdm>=4.67.1",
    "torch",
    "pandas>=2.3.0",
    "ipykernel>=6.29.5",
]
